import {readElectrical} from './full-checks.mjs';
// Focused r12 visual evidence on the actual candidate. Read-only model inspection;
// all view/state changes use the site's existing UI and real pointer/wheel input.
export async function runHardware({page,context,frame,report,row,shot,ready,activeFrame,target,remainingOnly=false}){
 const settle=()=>page.waitForTimeout(450);
 const mode=async value=>{await page.locator(`[data-assembly-command="mode"][data-value="${value}"]`).click();await frame.waitForFunction(v=>window.aikoAssemblyGuide.snapshot().mode===v,value);await settle();};
 const step=async n=>{const select=page.locator('[data-assembly-step-select]');if(await select.count())await select.selectOption(String(n));else {let current=await frame.evaluate(()=>window.aikoAssemblyGuide.snapshot().step);while(current!==n){const next=current+(n>current?1:-1);await page.locator(`[data-assembly-command="step"][data-value="${next}"]`).click();await frame.waitForFunction(n=>window.aikoAssemblyGuide.snapshot().step===n,next);current=next;}}await frame.waitForFunction(n=>window.aikoAssemblyGuide.snapshot().step===n,n);await settle();};
 const progress=async p=>{await page.locator('[data-assembly-progress]').evaluate((e,p)=>{e.value=String(p*100);e.dispatchEvent(new Event('input',{bubbles:true}));},p);await frame.waitForFunction(p=>Math.abs(window.aikoAssemblyGuide.snapshot().stepProgress-p)<.01,p);await settle();};
 const mouse=async(dx,dy,wheel=0)=>{const b=await frame.locator('canvas').first().boundingBox(),x=b.x+b.width*.53,y=b.y+b.height*.45;await page.mouse.move(x,y);if(dx||dy){await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:12});await page.mouse.up();}if(wheel)await page.mouse.wheel(0,wheel);await settle();};
 const actual=expression=>readElectrical(context,page,frame,expression);
 const inspect=`(()=>{scene.updateMatrixWorld(true);const nuts=objects.filter(o=>o.userData.commRearNut),washers=objects.filter(o=>/Chamfered flat washer/.test(o.name)),heads=objects.filter(o=>o.userData.commFixingHead),shafts=objects.filter(o=>o.userData.commFixingShaft);return {nuts:nuts.length,washers:washers.length,heads:heads.length,threaded:shafts.filter(o=>o.getObjectByName('Illustrative thread ridge')).length,shaftCount:shafts.length,nylon:nuts.filter(o=>o.getObjectByName('Blue nylon locking insert')).length,rails:commRails.map(o=>{const mesh=o.children.find(c=>c.isMesh);mesh.geometry.computeBoundingBox();return mesh.geometry.boundingBox.getSize(new THREE.Vector3()).x*mesh.getWorldScale(new THREE.Vector3()).x;}),boards:[cc1,cc2,cc3].map(o=>o.position.toArray()),camera:camera.position.toArray(),snapshot:window.aikoAssemblyGuide.snapshot()};})()`;
 const initial=await actual(inspect);report.model.hardware=initial;
 row('H1-hardware','实际螺栓组数量、螺纹、尼龙锁母和平垫',initial.nuts===10&&initial.washers===20&&initial.heads===10&&initial.nylon===10&&initial.threaded===initial.shaftCount?'通过':'失败',initial);
 row('H1-baseline','两根150mm导轨和三块恒流板L型',initial.rails.length===2&&initial.rails.every(v=>Math.abs(v-1.5)<1e-6)&&initial.boards[0][0]===initial.boards[1][0]&&initial.boards[2][0]<initial.boards[1][0]&&initial.boards[2][1]===initial.boards[1][1]?'通过':'失败',initial);
 if(!remainingOnly){
 await mode('animation');await step(2);await progress(.30);await mouse(0,0,-650);await shot('01-comm-socket-heads','导轨螺栓组：内六角、螺纹与通孔平垫',frame);
 const front=await actual('camera.position.toArray()');const b=await frame.locator('canvas').first().boundingBox();await mouse(b.width*.46,12,-250);const rear=await actual('camera.position.toArray()');await shot('02-comm-locknuts','实际旋转后的导轨后侧锁母和垫片',frame);row('H2-rotation','实际鼠标旋转有效',Math.hypot(...front.map((v,i)=>v-rear[i]))>.1?'通过':'失败',{front,rear});
 }else row('H2-previous','复用相同模型文件的通讯板前/后细节与鼠标旋转','待核实','源72d8e447运行37176709104已取得对应PNG；本次仅修测试步进控件，合并复核时核对资源哈希。');
 await page.locator('[data-assembly-command="select"][data-value="constant-aiko"]').click();await frame.waitForFunction(()=>window.aikoAssemblyGuide.snapshot().boardId==='constant-aiko');await mode('exploded');await mouse(0,0,-350);await shot('03-board-screws','恒流板安装螺丝：内六角与螺纹',frame);
 const gxURL=new URL(target);gxURL.searchParams.set('assembly','gx-touch50');await page.goto(gxURL.href,{waitUntil:'domcontentloaded'});frame=await activeFrame();await ready(frame);await frame.waitForFunction(()=>!!window.aikoGxScene);
 const gx=()=>frame.evaluate(()=>{const a=window.aikoGxScene,all=[];a.scene.traverse(o=>all.push(o));return {center:a.gxTouch.group.position.toArray(),height:a.gxTouch.group.position.y-a.gxTouch.spec.floorY,fixings:a.gxTouch.fixings.length,frameHoles:a.gxTouch.mount.children[0].geometry.parameters.shapes.holes.length,ferrites:a.assembly.ferrites.map(o=>({endpoint:o.userData.endpoint,angle:o.userData.hinge.rotation.y,cores:o.getObjectsByProperty('name','Ferrite half-core with open cable groove').length})),hdmiContacts:all.filter(o=>o.name==='HDMI contact').length,usbContacts:all.filter(o=>o.name==='USB-A contact').length,plugs:['hdmi-plug','usb-plug'].map(id=>a.assembly.parts[id][0].position.toArray()),snapshot:window.aikoAssemblyGuide.snapshot()};});
 await mode('animation');await step(5);await progress(.30);await mouse(25,12,-650);await shot('04-gx-frame','GX原厂固定框：圆角、真实开口、两组孔和前侧螺钉',frame);
 let result=await gx();report.model.gxHardware=result;row('H3-frame','GX固定框开口、两组孔、四颗前侧螺钉及1450mm高度',result.frameHoles===9&&result.fixings===4&&Math.abs(result.height-1.45)<1e-6?'通过':'失败',result);
 await step(6);await progress(.35);await mouse(0,0,-600);const opened=await gx();await shot('05-ferrite-open','屏幕侧磁环打开：两半磁芯、穿线槽、铰链和锁扣',frame);
 await progress(1);const closed=await gx();await shot('06-ferrite-closed','屏幕侧磁环闭合，线缆穿过中心孔',frame);row('H4-ferrites','两只磁环、两半磁芯及实际开合',opened.ferrites.length===2&&opened.ferrites.every(o=>o.cores===2)&&Math.abs(opened.ferrites[0].angle)>.1&&closed.ferrites[0].angle===0?'通过':'失败',{opened:opened.ferrites,closed:closed.ferrites});
 await step(9);await progress(0);await mouse(0,0,-1400);const unplugged=await gx();await shot('07-connectors-open','HDMI梯形空心壳、USB-A插头和对应插口',frame);
 await progress(1);const plugged=await gx();await shot('08-connectors-seated','HDMI显示与USB供电插接完成',frame);row('H5-connectors','HDMI/USB触点及实际插接运动',plugged.hdmiContacts===19&&plugged.usbContacts===4&&unplugged.plugs.every((p,i)=>Math.abs(p[0]-plugged.plugs[i][0])>.01)?'通过':'失败',{unplugged,plugged});
 row('H6-visual','配件外形、清晰度与动画细节','待核实','取回以上实际PNG逐图复核；没有实测的框厚、磁环包络及最终固定规格仍是示意，不是制造数据。');
}
